export const wordCategories = [
  { id:"animal", label:"動物", icon:"🐾" },
  { id:"food", label:"食物飲料", icon:"🍽️" },
  { id:"family", label:"家人與人物", icon:"👨‍👩‍👧" },
  { id:"school", label:"學校用品", icon:"🏫" },
  { id:"body", label:"身體", icon:"🖐️" },
  { id:"clothes", label:"衣物", icon:"👕" },
  { id:"color", label:"顏色", icon:"🎨" },
  { id:"number", label:"數字", icon:"🔢" },
  { id:"nature", label:"自然天氣", icon:"🌤️" },
  { id:"action", label:"動作", icon:"🏃" },
  { id:"feeling", label:"感受形容", icon:"😊" },
  { id:"daily", label:"生活用品", icon:"🏠" },
  { id:"place", label:"地點交通", icon:"🚌" },
  { id:"time", label:"時間日期", icon:"🕐" },
  { id:"basic", label:"基礎用語", icon:"💬" },
] as const;

export type WordCategory = typeof wordCategories[number]["id"];
export type WordCard = { word:string; zh:string; emoji:string; image?:string; category:WordCategory };

// 新增單字只要加一筆資料；image 可填 public 裡的圖片路徑，未填時顯示 emoji。
export const words:WordCard[] = [
  // 動物
  {emoji:"🐱",word:"cat",zh:"貓",category:"animal"},{emoji:"🐶",word:"dog",zh:"狗",category:"animal"},
  {emoji:"🐦",word:"bird",zh:"鳥",category:"animal"},{emoji:"🐟",word:"fish",zh:"魚",category:"animal"},
  {emoji:"🐰",word:"rabbit",zh:"兔子",category:"animal"},{emoji:"🦆",word:"duck",zh:"鴨子",category:"animal"},
  {emoji:"🐔",word:"chicken",zh:"雞",category:"animal"},{emoji:"🐮",word:"cow",zh:"乳牛",category:"animal"},
  {emoji:"🐷",word:"pig",zh:"豬",category:"animal"},{emoji:"🐴",word:"horse",zh:"馬",category:"animal"},
  {emoji:"🐑",word:"sheep",zh:"綿羊",category:"animal"},{emoji:"🐐",word:"goat",zh:"山羊",category:"animal"},
  {emoji:"🐵",word:"monkey",zh:"猴子",category:"animal"},{emoji:"🦁",word:"lion",zh:"獅子",category:"animal"},
  {emoji:"🐯",word:"tiger",zh:"老虎",category:"animal"},{emoji:"🐘",word:"elephant",zh:"大象",category:"animal"},
  {emoji:"🐻",word:"bear",zh:"熊",category:"animal"},{emoji:"🐼",word:"panda",zh:"貓熊",category:"animal"},
  {emoji:"🐸",word:"frog",zh:"青蛙",category:"animal"},{emoji:"🐢",word:"turtle",zh:"烏龜",category:"animal"},
  {emoji:"🦋",word:"butterfly",zh:"蝴蝶",category:"animal"},{emoji:"🐝",word:"bee",zh:"蜜蜂",category:"animal"},
  {emoji:"🐜",word:"ant",zh:"螞蟻",category:"animal"},{emoji:"🐍",word:"snake",zh:"蛇",category:"animal"},

  // 食物與飲料
  {emoji:"🍎",word:"apple",zh:"蘋果",category:"food"},{emoji:"🍌",word:"banana",zh:"香蕉",category:"food"},
  {emoji:"🍊",word:"orange",zh:"柳橙",category:"food"},{emoji:"🍇",word:"grape",zh:"葡萄",category:"food"},
  {emoji:"🍉",word:"watermelon",zh:"西瓜",category:"food"},{emoji:"🍓",word:"strawberry",zh:"草莓",category:"food"},
  {emoji:"🍐",word:"pear",zh:"梨子",category:"food"},{emoji:"🍑",word:"peach",zh:"桃子",category:"food"},
  {emoji:"🍋",word:"lemon",zh:"檸檬",category:"food"},{emoji:"🥭",word:"mango",zh:"芒果",category:"food"},
  {emoji:"🍚",word:"rice",zh:"米飯",category:"food"},{emoji:"🍞",word:"bread",zh:"麵包",category:"food"},
  {emoji:"🎂",word:"cake",zh:"蛋糕",category:"food"},{emoji:"🍪",word:"cookie",zh:"餅乾",category:"food"},
  {emoji:"🍬",word:"candy",zh:"糖果",category:"food"},{emoji:"🥚",word:"egg",zh:"蛋",category:"food"},
  {emoji:"🥛",word:"milk",zh:"牛奶",category:"food"},{emoji:"🧃",word:"juice",zh:"果汁",category:"food"},
  {emoji:"💧",word:"water",zh:"水",category:"food"},{emoji:"🍵",word:"tea",zh:"茶",category:"food"},
  {emoji:"🥣",word:"soup",zh:"湯",category:"food"},{emoji:"🍔",word:"hamburger",zh:"漢堡",category:"food"},
  {emoji:"🍕",word:"pizza",zh:"披薩",category:"food"},{emoji:"🍜",word:"noodle",zh:"麵條",category:"food"},
  {emoji:"🥗",word:"salad",zh:"沙拉",category:"food"},{emoji:"🥪",word:"sandwich",zh:"三明治",category:"food"},
  {emoji:"🥕",word:"carrot",zh:"紅蘿蔔",category:"food"},{emoji:"🥔",word:"potato",zh:"馬鈴薯",category:"food"},
  {emoji:"🍅",word:"tomato",zh:"番茄",category:"food"},{emoji:"🧀",word:"cheese",zh:"起司",category:"food"},

  // 家人與人物
  {emoji:"👨‍👩‍👧",word:"family",zh:"家庭",category:"family"},{emoji:"👨",word:"father",zh:"父親",category:"family"},
  {emoji:"👩",word:"mother",zh:"母親",category:"family"},{emoji:"👨",word:"dad",zh:"爸爸",category:"family"},
  {emoji:"👩",word:"mom",zh:"媽媽",category:"family"},{emoji:"👦",word:"brother",zh:"兄弟",category:"family"},
  {emoji:"👧",word:"sister",zh:"姊妹",category:"family"},{emoji:"👴",word:"grandfather",zh:"祖父",category:"family"},
  {emoji:"👵",word:"grandmother",zh:"祖母",category:"family"},{emoji:"👴",word:"grandpa",zh:"爺爺／外公",category:"family"},
  {emoji:"👵",word:"grandma",zh:"奶奶／外婆",category:"family"},{emoji:"👨",word:"uncle",zh:"叔叔／舅舅",category:"family"},
  {emoji:"👩",word:"aunt",zh:"阿姨／姑姑",category:"family"},{emoji:"👶",word:"baby",zh:"嬰兒",category:"family"},
  {emoji:"👦",word:"boy",zh:"男孩",category:"family"},{emoji:"👧",word:"girl",zh:"女孩",category:"family"},
  {emoji:"👨",word:"man",zh:"男人",category:"family"},{emoji:"👩",word:"woman",zh:"女人",category:"family"},
  {emoji:"🧒",word:"child",zh:"小孩",category:"family"},{emoji:"🧑‍🤝‍🧑",word:"friend",zh:"朋友",category:"family"},

  // 學校
  {emoji:"📚",word:"book",zh:"書",category:"school"},{emoji:"✏️",word:"pencil",zh:"鉛筆",category:"school"},
  {emoji:"🖊️",word:"pen",zh:"原子筆",category:"school"},{emoji:"📏",word:"ruler",zh:"尺",category:"school"},
  {emoji:"◻️",word:"eraser",zh:"橡皮擦",category:"school"},{emoji:"🎒",word:"bag",zh:"書包",category:"school"},
  {emoji:"🗄️",word:"desk",zh:"書桌",category:"school"},{emoji:"🪑",word:"chair",zh:"椅子",category:"school"},
  {emoji:"🪵",word:"table",zh:"桌子",category:"school"},{emoji:"📄",word:"paper",zh:"紙",category:"school"},
  {emoji:"🖍️",word:"crayon",zh:"蠟筆",category:"school"},{emoji:"🖍️",word:"marker",zh:"彩色筆",category:"school"},
  {emoji:"✂️",word:"scissors",zh:"剪刀",category:"school"},{emoji:"🧴",word:"glue",zh:"膠水",category:"school"},
  {emoji:"🏫",word:"classroom",zh:"教室",category:"school"},{emoji:"🏫",word:"school",zh:"學校",category:"school"},
  {emoji:"🧑‍🏫",word:"teacher",zh:"老師",category:"school"},{emoji:"🧑‍🎓",word:"student",zh:"學生",category:"school"},
  {emoji:"📝",word:"homework",zh:"家庭作業",category:"school"},{emoji:"❓",word:"question",zh:"問題",category:"school"},

  // 身體
  {emoji:"🙂",word:"head",zh:"頭",category:"body"},{emoji:"💇",word:"hair",zh:"頭髮",category:"body"},
  {emoji:"🙂",word:"face",zh:"臉",category:"body"},{emoji:"👁️",word:"eye",zh:"眼睛",category:"body"},
  {emoji:"👂",word:"ear",zh:"耳朵",category:"body"},{emoji:"👃",word:"nose",zh:"鼻子",category:"body"},
  {emoji:"👄",word:"mouth",zh:"嘴巴",category:"body"},{emoji:"🦷",word:"tooth",zh:"牙齒",category:"body"},
  {emoji:"🧣",word:"neck",zh:"脖子",category:"body"},{emoji:"🤷",word:"shoulder",zh:"肩膀",category:"body"},
  {emoji:"💪",word:"arm",zh:"手臂",category:"body"},{emoji:"🖐️",word:"hand",zh:"手",category:"body"},
  {emoji:"☝️",word:"finger",zh:"手指",category:"body"},{emoji:"🦵",word:"leg",zh:"腿",category:"body"},
  {emoji:"🦶",word:"foot",zh:"腳",category:"body"},{emoji:"🦵",word:"knee",zh:"膝蓋",category:"body"},
  {emoji:"🧍",word:"body",zh:"身體",category:"body"},{emoji:"❤️",word:"heart",zh:"心臟",category:"body"},

  // 衣物
  {emoji:"👕",word:"shirt",zh:"襯衫",category:"clothes"},{emoji:"👕",word:"T-shirt",zh:"T恤",category:"clothes"},
  {emoji:"👖",word:"pants",zh:"長褲",category:"clothes"},{emoji:"🩳",word:"shorts",zh:"短褲",category:"clothes"},
  {emoji:"👗",word:"skirt",zh:"裙子",category:"clothes"},{emoji:"👗",word:"dress",zh:"洋裝",category:"clothes"},
  {emoji:"🧥",word:"coat",zh:"外套",category:"clothes"},{emoji:"🧥",word:"jacket",zh:"夾克",category:"clothes"},
  {emoji:"👟",word:"shoes",zh:"鞋子",category:"clothes"},{emoji:"🧦",word:"socks",zh:"襪子",category:"clothes"},
  {emoji:"🎩",word:"hat",zh:"帽子",category:"clothes"},{emoji:"🧢",word:"cap",zh:"鴨舌帽",category:"clothes"},
  {emoji:"🧶",word:"sweater",zh:"毛衣",category:"clothes"},{emoji:"🥋",word:"uniform",zh:"制服",category:"clothes"},
  {emoji:"👓",word:"glasses",zh:"眼鏡",category:"clothes"},{emoji:"☂️",word:"umbrella",zh:"雨傘",category:"clothes"},

  // 顏色
  {emoji:"🔴",word:"red",zh:"紅色",category:"color"},{emoji:"🔵",word:"blue",zh:"藍色",category:"color"},
  {emoji:"🟢",word:"green",zh:"綠色",category:"color"},{emoji:"🟡",word:"yellow",zh:"黃色",category:"color"},
  {emoji:"🟣",word:"purple",zh:"紫色",category:"color"},{emoji:"🌸",word:"pink",zh:"粉紅色",category:"color"},
  {emoji:"🟤",word:"brown",zh:"棕色",category:"color"},{emoji:"⚫",word:"black",zh:"黑色",category:"color"},
  {emoji:"⚪",word:"white",zh:"白色",category:"color"},{emoji:"🩶",word:"gray",zh:"灰色",category:"color"},

  // 數字
  {emoji:"1️⃣",word:"one",zh:"一",category:"number"},{emoji:"2️⃣",word:"two",zh:"二",category:"number"},
  {emoji:"3️⃣",word:"three",zh:"三",category:"number"},{emoji:"4️⃣",word:"four",zh:"四",category:"number"},
  {emoji:"5️⃣",word:"five",zh:"五",category:"number"},{emoji:"6️⃣",word:"six",zh:"六",category:"number"},
  {emoji:"7️⃣",word:"seven",zh:"七",category:"number"},{emoji:"8️⃣",word:"eight",zh:"八",category:"number"},
  {emoji:"9️⃣",word:"nine",zh:"九",category:"number"},{emoji:"🔟",word:"ten",zh:"十",category:"number"},
  {emoji:"1️⃣1️⃣",word:"eleven",zh:"十一",category:"number"},{emoji:"1️⃣2️⃣",word:"twelve",zh:"十二",category:"number"},
  {emoji:"1️⃣3️⃣",word:"thirteen",zh:"十三",category:"number"},{emoji:"1️⃣4️⃣",word:"fourteen",zh:"十四",category:"number"},
  {emoji:"1️⃣5️⃣",word:"fifteen",zh:"十五",category:"number"},{emoji:"1️⃣6️⃣",word:"sixteen",zh:"十六",category:"number"},
  {emoji:"1️⃣7️⃣",word:"seventeen",zh:"十七",category:"number"},{emoji:"1️⃣8️⃣",word:"eighteen",zh:"十八",category:"number"},
  {emoji:"1️⃣9️⃣",word:"nineteen",zh:"十九",category:"number"},{emoji:"2️⃣0️⃣",word:"twenty",zh:"二十",category:"number"},

  // 自然與天氣
  {emoji:"☀️",word:"sun",zh:"太陽",category:"nature"},{emoji:"🌙",word:"moon",zh:"月亮",category:"nature"},
  {emoji:"⭐",word:"star",zh:"星星",category:"nature"},{emoji:"🌌",word:"sky",zh:"天空",category:"nature"},
  {emoji:"☁️",word:"cloud",zh:"雲",category:"nature"},{emoji:"🌧️",word:"rain",zh:"雨",category:"nature"},
  {emoji:"💨",word:"wind",zh:"風",category:"nature"},{emoji:"🌳",word:"tree",zh:"樹",category:"nature"},
  {emoji:"🌸",word:"flower",zh:"花",category:"nature"},{emoji:"🌱",word:"grass",zh:"草",category:"nature"},
  {emoji:"🍃",word:"leaf",zh:"葉子",category:"nature"},{emoji:"⛰️",word:"mountain",zh:"山",category:"nature"},
  {emoji:"🏞️",word:"river",zh:"河流",category:"nature"},{emoji:"🌊",word:"sea",zh:"海",category:"nature"},
  {emoji:"🏖️",word:"beach",zh:"海灘",category:"nature"},{emoji:"🔥",word:"fire",zh:"火",category:"nature"},
  {emoji:"❄️",word:"snow",zh:"雪",category:"nature"},{emoji:"🌤️",word:"sunny",zh:"晴朗的",category:"nature"},
  {emoji:"🌧️",word:"rainy",zh:"下雨的",category:"nature"},{emoji:"☁️",word:"cloudy",zh:"多雲的",category:"nature"},
  {emoji:"💨",word:"windy",zh:"有風的",category:"nature"},{emoji:"🌡️",word:"weather",zh:"天氣",category:"nature"},

  // 動作
  {emoji:"🏃",word:"run",zh:"跑",category:"action"},{emoji:"🚶",word:"walk",zh:"走路",category:"action"},
  {emoji:"🤸",word:"jump",zh:"跳",category:"action"},{emoji:"🏊",word:"swim",zh:"游泳",category:"action"},
  {emoji:"🎤",word:"sing",zh:"唱歌",category:"action"},{emoji:"💃",word:"dance",zh:"跳舞",category:"action"},
  {emoji:"📖",word:"read",zh:"閱讀",category:"action"},{emoji:"✍️",word:"write",zh:"書寫",category:"action"},
  {emoji:"🎨",word:"draw",zh:"畫圖",category:"action"},{emoji:"🍽️",word:"eat",zh:"吃",category:"action"},
  {emoji:"🥤",word:"drink",zh:"喝",category:"action"},{emoji:"😴",word:"sleep",zh:"睡覺",category:"action"},
  {emoji:"🪑",word:"sit",zh:"坐",category:"action"},{emoji:"🧍",word:"stand",zh:"站",category:"action"},
  {emoji:"📂",word:"open",zh:"打開",category:"action"},{emoji:"📕",word:"close",zh:"關閉",category:"action"},
  {emoji:"👀",word:"look",zh:"看",category:"action"},{emoji:"👂",word:"listen",zh:"聽",category:"action"},
  {emoji:"🗣️",word:"speak",zh:"說話",category:"action"},{emoji:"⚽",word:"play",zh:"玩",category:"action"},
  {emoji:"📘",word:"study",zh:"讀書",category:"action"},{emoji:"🤝",word:"help",zh:"幫助",category:"action"},
  {emoji:"🧼",word:"wash",zh:"清洗",category:"action"},{emoji:"🧹",word:"clean",zh:"清潔",category:"action"},
  {emoji:"👨‍🍳",word:"cook",zh:"烹飪",category:"action"},{emoji:"🚲",word:"ride",zh:"騎乘",category:"action"},
  {emoji:"🪽",word:"fly",zh:"飛",category:"action"},{emoji:"😊",word:"smile",zh:"微笑",category:"action"},
  {emoji:"😭",word:"cry",zh:"哭",category:"action"},{emoji:"👏",word:"clap",zh:"拍手",category:"action"},

  // 感受與形容詞
  {emoji:"😊",word:"happy",zh:"開心的",category:"feeling"},{emoji:"😢",word:"sad",zh:"難過的",category:"feeling"},
  {emoji:"😠",word:"angry",zh:"生氣的",category:"feeling"},{emoji:"🥱",word:"tired",zh:"疲倦的",category:"feeling"},
  {emoji:"🤤",word:"hungry",zh:"飢餓的",category:"feeling"},{emoji:"🥵",word:"thirsty",zh:"口渴的",category:"feeling"},
  {emoji:"😨",word:"scared",zh:"害怕的",category:"feeling"},{emoji:"🤒",word:"sick",zh:"生病的",category:"feeling"},
  {emoji:"👍",word:"good",zh:"好的",category:"feeling"},{emoji:"👎",word:"bad",zh:"不好的",category:"feeling"},
  {emoji:"🐘",word:"big",zh:"大的",category:"feeling"},{emoji:"🐜",word:"small",zh:"小的",category:"feeling"},
  {emoji:"🦒",word:"tall",zh:"高的",category:"feeling"},{emoji:"🐹",word:"short",zh:"矮／短的",category:"feeling"},
  {emoji:"📏",word:"long",zh:"長的",category:"feeling"},{emoji:"✨",word:"new",zh:"新的",category:"feeling"},
  {emoji:"🏚️",word:"old",zh:"舊的／年老的",category:"feeling"},{emoji:"🧒",word:"young",zh:"年輕的",category:"feeling"},
  {emoji:"🌺",word:"beautiful",zh:"美麗的",category:"feeling"},{emoji:"🐣",word:"cute",zh:"可愛的",category:"feeling"},
  {emoji:"🏎️",word:"fast",zh:"快的",category:"feeling"},{emoji:"🐌",word:"slow",zh:"慢的",category:"feeling"},
  {emoji:"🧽",word:"dirty",zh:"骯髒的",category:"feeling"},{emoji:"🌡️",word:"hot",zh:"熱的",category:"feeling"},
  {emoji:"🧊",word:"cold",zh:"冷的",category:"feeling"},{emoji:"🤗",word:"warm",zh:"溫暖的",category:"feeling"},
  {emoji:"😎",word:"cool",zh:"涼爽的／酷的",category:"feeling"},{emoji:"💪",word:"strong",zh:"強壯的",category:"feeling"},

  // 生活用品
  {emoji:"🏠",word:"house",zh:"房子",category:"daily"},{emoji:"🏡",word:"home",zh:"家",category:"daily"},
  {emoji:"🚪",word:"room",zh:"房間",category:"daily"},{emoji:"🛏️",word:"bedroom",zh:"臥室",category:"daily"},
  {emoji:"🛁",word:"bathroom",zh:"浴室",category:"daily"},{emoji:"🍳",word:"kitchen",zh:"廚房",category:"daily"},
  {emoji:"🚪",word:"door",zh:"門",category:"daily"},{emoji:"🪟",word:"window",zh:"窗戶",category:"daily"},
  {emoji:"🛏️",word:"bed",zh:"床",category:"daily"},{emoji:"💡",word:"lamp",zh:"燈",category:"daily"},
  {emoji:"🕰️",word:"clock",zh:"時鐘",category:"daily"},{emoji:"📱",word:"phone",zh:"電話",category:"daily"},
  {emoji:"💻",word:"computer",zh:"電腦",category:"daily"},{emoji:"📺",word:"television",zh:"電視",category:"daily"},
  {emoji:"🧸",word:"toy",zh:"玩具",category:"daily"},{emoji:"⚽",word:"ball",zh:"球",category:"daily"},
  {emoji:"🎁",word:"gift",zh:"禮物",category:"daily"},{emoji:"📦",word:"box",zh:"盒子",category:"daily"},
  {emoji:"🔑",word:"key",zh:"鑰匙",category:"daily"},{emoji:"📷",word:"camera",zh:"相機",category:"daily"},

  // 地點與交通
  {emoji:"🚗",word:"car",zh:"汽車",category:"place"},{emoji:"🚌",word:"bus",zh:"公車",category:"place"},
  {emoji:"🚲",word:"bike",zh:"腳踏車",category:"place"},{emoji:"🚆",word:"train",zh:"火車",category:"place"},
  {emoji:"✈️",word:"plane",zh:"飛機",category:"place"},{emoji:"🚢",word:"ship",zh:"船",category:"place"},
  {emoji:"🏞️",word:"park",zh:"公園",category:"place"},{emoji:"🦒",word:"zoo",zh:"動物園",category:"place"},
  {emoji:"🏪",word:"store",zh:"商店",category:"place"},{emoji:"🏥",word:"hospital",zh:"醫院",category:"place"},
  {emoji:"📚",word:"library",zh:"圖書館",category:"place"},{emoji:"🍽️",word:"restaurant",zh:"餐廳",category:"place"},
  {emoji:"🏦",word:"bank",zh:"銀行",category:"place"},{emoji:"📮",word:"post",zh:"郵局／郵件",category:"place"},
  {emoji:"🛣️",word:"street",zh:"街道",category:"place"},{emoji:"🌆",word:"city",zh:"城市",category:"place"},

  // 時間日期
  {emoji:"🌅",word:"morning",zh:"早上",category:"time"},{emoji:"☀️",word:"afternoon",zh:"下午",category:"time"},
  {emoji:"🌇",word:"evening",zh:"傍晚",category:"time"},{emoji:"🌙",word:"night",zh:"夜晚",category:"time"},
  {emoji:"📅",word:"today",zh:"今天",category:"time"},{emoji:"➡️",word:"tomorrow",zh:"明天",category:"time"},
  {emoji:"⬅️",word:"yesterday",zh:"昨天",category:"time"},{emoji:"🕐",word:"time",zh:"時間",category:"time"},
  {emoji:"☀️",word:"day",zh:"白天／日",category:"time"},{emoji:"📆",word:"week",zh:"星期",category:"time"},
  {emoji:"🗓️",word:"month",zh:"月份",category:"time"},{emoji:"🎆",word:"year",zh:"年",category:"time"},
  {emoji:"🌱",word:"spring",zh:"春天",category:"time"},{emoji:"🏖️",word:"summer",zh:"夏天",category:"time"},
  {emoji:"🍂",word:"fall",zh:"秋天",category:"time"},{emoji:"⛄",word:"winter",zh:"冬天",category:"time"},

  // 基礎用語
  {emoji:"👋",word:"hello",zh:"哈囉",category:"basic"},{emoji:"👋",word:"hi",zh:"嗨",category:"basic"},
  {emoji:"👋",word:"goodbye",zh:"再見",category:"basic"},{emoji:"🙏",word:"please",zh:"請",category:"basic"},
  {emoji:"🙇",word:"thanks",zh:"謝謝",category:"basic"},{emoji:"😔",word:"sorry",zh:"對不起",category:"basic"},
  {emoji:"✅",word:"yes",zh:"是",category:"basic"},{emoji:"❌",word:"no",zh:"不是／不",category:"basic"},
  {emoji:"🏷️",word:"name",zh:"名字",category:"basic"},{emoji:"👇",word:"this",zh:"這個",category:"basic"},
  {emoji:"👉",word:"that",zh:"那個",category:"basic"},{emoji:"❓",word:"what",zh:"什麼",category:"basic"},
  {emoji:"👤",word:"who",zh:"誰",category:"basic"},{emoji:"📍",word:"where",zh:"哪裡",category:"basic"},
  {emoji:"🤔",word:"how",zh:"如何",category:"basic"},{emoji:"1️⃣",word:"first",zh:"第一／首先",category:"basic"},
  {emoji:"➕",word:"more",zh:"更多",category:"basic"},{emoji:"🫶",word:"love",zh:"喜愛",category:"basic"},
];
